### ISSUE TITLE
SKIDDED WOW

### ISSUE THREAD

**Issue by ItsNeverLand** [ignJosh/NightVision#2]
https://user-images.githubusercontent.com/66177453/131424833-825961ee-5395-4206-88aa-dd4d8d6192c6.mp4

**Comment by ignJosh** [comment]
>  file.mp4

YOU'RE LITERALLY OBSESSED WITH ME GO THE FUCK AWAY

**Comment by ItsNeverLand** [comment]
![image](https://user-images.githubusercontent.com/66177453/131427289-5b5de428-3d26-4997-95ce-21cc75ce986b.png)

**Comment by ItsNeverLand** [comment]
look whos talking
